version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 14
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: build
      include: scope
  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: weekly
    cooldown:
      default-days: 14
    groups:
      python-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: build
      include: scope
