name: Validate Documentation Build

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: derekwinters/chores-web-actions/actions/setup-python@19729c4d6ee3366dc32f4bd8946cb8ac7f6b05e5
        with:
          requirements-path: docs/requirements.txt
      - name: Install dependencies
        run: pip install -r docs/requirements.txt
      - name: Build documentation
        run: mkdocs build --strict
